name: Deploy to Vercel

on:
  push:
      branches:
            - master

            jobs:
              deploy:
                  runs-on: ubuntu-latest
                      steps:
                            - name: Trigger Vercel Deploy Hook
                                    run: |
                                              curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_cinAzy9USNA2H7rd2MpuNlzNN72g/Urxm2fj18T"
